### ISSUE TITLE
Im having an issue with this line 

### ISSUE THREAD

**Issue by bechampion** [Lochnair/xt_tls#12]
https://github.com/Lochnair/xt_tls/blob/775afc507ea39de85627cc87d6da79fe247c23aa/src/xt_tls.c#L34

I fall in the first EPROTO if , any clues?

Thank you!

**Comment by Lochnair** [comment]
I need a TCPdump/WireShark capture to look at, to debug this further.

**Comment by Lochnair** [comment]
Closed due to inactivity.
