### ISSUE TITLE
Create OpenWrt package

### ISSUE THREAD

**Issue by reinerotto** [Lochnair/xt_tls#14]
Will be appreciated.

**Comment by Anthropohedron** [comment]
This repo doesn't seem to have been touched for over a year. Is there any chance of an OpenWRT package happening?

**Comment by Lochnair** [comment]
Threw together a feed that anyone interested can try (add to feeds.conf): 
```
src-git lochnair https://github.com/Lochnair/openwrt-feeds.git
```

Haven't had time to test yet, but it does seemingly get the packages right.
Also it won't show up in the right places as of yet. The kernel part is in "Kernel modules -> Other modules" and the userspace part in "Network".

**Comment by TA4APJ** [comment]
> > Threw together a feed that anyone interested can try (add to feeds.conf):
> > ```
> > src-git lochnair https://github.com/Lochnair/openwrt-feeds.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Haven't had time to test yet, but it does seemingly get the packages right. Also it won't show up in the right places as of yet. The kernel part is in "Kernel modules -> Other modules" and the userspace part in "Network".
> 
> Hi, I compiled and tested it on Openwrt 21.02.3, iptables can't find the tls module, and the kernel module is there, did I do something wrong? ![Screenshot_20220524-163509_JuiceSSH](https://user-images.githubusercontent.com/57648531/169987827-e490ff3e-5188-49a5-8cd5-5ddc70e28e40.png) ![Screenshot_20220524-163110_JuiceSSH_1](https://user-images.githubusercontent.com/57648531/169987843-e99ba49d-ab05-4386-8c6c-4484d222c718.png) I compiled these two ![Screenshot_20220524-163101_Chrome_1](https://user-images.githubusercontent.com/57648531/169988099-84a4563f-d962-4c1f-88cb-0da146b2c54a.png)

Hi I am currently working on xt_tls 
Could you help me building for OpenWrt ?

**Comment by TA4APJ** [comment]
> iptables can't find the tls module

Hi i solved this problem 

Problem caused by  **libxt_tls.so**  so this file must be in  `/usr/lib/iptables` directory.
`cp /usr/lib/xtables/libxt_tls.so /usr/lib/iptables`

```
root@OpenWrt:/usr/lib# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       tcp  --  anywhere             anywhere             tcp dpt:https TLS match host *.googlevideo.com

```

**Comment by Lochnair** [comment]
I've updated the package to the latest version and corrected the path
