### ISSUE TITLE
Feature request: xt_TLS (TLS SNI field altering/discarding)

### ISSUE THREAD

**Issue by LGA1150** [Lochnair/xt_tls#16]
It may be useful for bypassing TLS SNI filtering.
Possible usage:
SNI field altering:
```
iptables -A OUTPUT -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j TLS --set-host "www.google.com"
```

SNI field discarding:
```
iptables -A OUTPUT -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j TLS --drop-host
```

**Comment by Lochnair** [comment]
I don't see how one would be able to utilize this (at least not with "normal" browsers/servers). Properly configured servers only serves valid responses for the domains it was set up for. So if you send open a TLS connection to www.facebook.com and change the SNI field to www.google.com, the Facebook servers will have no idea what you're asking for and'll return a 404.

**Comment by LGA1150** [comment]
After hours of work I found that any altering on SNI will cause handshake failure, no matter whether packet length is changed or not.
Does TLS have checksum or something?

**Comment by LGA1150** [comment]
Seems that both client and server verify the previous handshake information in `Encrypted Handshake Message`, so this message should also be recalculated, which would be much more difficult because we need to track the whole handshake process.

Closing this issue for now.
