### ISSUE TITLE
ip6tables support

### ISSUE THREAD

**Issue by LGA1150** [Lochnair/xt_tls#17]
https://github.com/Lochnair/xt_tls/blob/775afc507ea39de85627cc87d6da79fe247c23aa/ipt/libxt_tls.c#L67
Change it to `NFPROTO_UNSPEC`

**Comment by Lochnair** [comment]
Fixed in https://github.com/Lochnair/xt_tls/commit/acb7c6ac6c462f673cc01e8e78d2a201421f43ca.
