### ISSUE TITLE
Destination based TLS forwarding

### ISSUE THREAD

**Issue by col-panic** [Lochnair/xt_tls#19]
After getting your module to run, I try to realize the following scenario:

I have an nginx running on the machine listening on port 443. Using your module i want to redirect any incoming tls traffic for host a.b.c to an internal machine (10.89.0.2), while leaving the other tls traffic being redirected to the local nginx.

Configuring the rule like
```
iptables -t nat -A PREROUTING -p tcp --dport 443 -m tls --tls-host "a.b.c" -j DNAT --to 10.89.0.2:8480
```
however, does not redirect me  to the configured host, but leaves me with nginx answering. I checked for server_name extension to be available - requests are done using Chrome. 

Am I missing something obvious? Is the module useable in this scenario?

**Comment by Lochnair** [comment]
I'm afraid not. The TCP session is already established when that rule matches, and you can't change destination/source addresses after the session is opened.

**Comment by col-panic** [comment]
Thanks a lot for clarifying this!
