### ISSUE TITLE
Error with openWRT: xt_tls: Unknown symbol glob_match (err 0)

### ISSUE THREAD

**Issue by whitetiger21022014** [Lochnair/xt_tls#20]
Hi All,
I use https://github.com/Love4Taylor/openwrt-xt_tls for creating OpenWRT's firmware
iptables -A OUTPUT -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j DROP
Error: iptables: No chain/target/match by that name.

Then I did more test:
modprobe xt-tls
1 module could not be probed
- xt_tls
----> It means can not load xt-tls module

dmesg I have
xt_tls: Unknown symbol glob_match (err 0)

kernel: 3.18.27 #177 Sun Oct 21 10:14:18 ICT 2018 mips n
This openWRT in bridge mode
Thanks

**Comment by Lochnair** [comment]
xt_tls relies on the kernels glob_match function for wildcard matching, but it seems it's not enabled in your kernel.

You should have `CONFIG_GLOB=y` set in the kernel config.

**Comment by whitetiger21022014** [comment]
Thank you,
I will try CONFIG_GLOB=y and let you know

**Comment by whitetiger21022014** [comment]
Enable CONFIG_GLOB=y in kernel (via Kconfig/.config), It works. Thanks

**Comment by alexalenberg** [comment]
> Enable CONFIG_GLOB=y in kernel (via Kconfig/.config), It works. Thanks

Is there a chance you can expand on how you enabled CONFIG_GLOB in the kernel? I am trying to build for ar71xx with not much luck...

**Comment by Lochnair** [comment]
@alexalenberg I think what @whitetiger21022014 did was to add `CONFIG_GLOB=y` to the .config manually, because you can't enable it with kernel_menuconfig (see [here](https://github.com/torvalds/linux/blob/master/lib/Kconfig#L472)).

So for OpenWrt with 4.14 kernel you would do
```bash
echo CONFIG_GLOB=y >> target/linux/generic/config-4.14
```
in the OpenWrt source folder.

**Comment by alexalenberg** [comment]
> @alexalenberg I think what @whitetiger21022014 did was to add `CONFIG_GLOB=y` to the .config manually, because you can't enable it with kernel_menuconfig (see [here](https://github.com/torvalds/linux/blob/master/lib/Kconfig#L472)).
> 
> So for OpenWrt with 4.14 kernel you would do
> 
> ```shell
> echo CONFIG_GLOB=y >> target/linux/generic/config-4.14
> ```
> 
> in the OpenWrt source folder.

Thank you @Lochnair, this is what I am doing (also tested different platforms). No luck with getting CONFIG_GLOB enabled in kernel. Will investigate more.
