### ISSUE TITLE
Does xt_tls support for forward/prerouting chain?

### ISSUE THREAD

**Issue by whitetiger21022014** [Lochnair/xt_tls#22]
Dear Lochnair,
I just tested, xt_tls supports with OUTPUT chain, but it can't work with FORWARD/PREROUTING chain
Does xt_tls support for FORWARD/PREROUTING chain, server has 2 NIC cards
Thanks

**Comment by whitetiger21022014** [comment]
Hi @luigi1809,
I tested on OpenWRT box as below:
**1. If box in routed mode (2 separate networks with eth0, eth1):** 
**cmd works :** iptables -I FORWARD -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j DROP

**2. If box in Bridged mode (same network between eth0 and eth1)**
**cmd doesn't works :** iptables -I FORWARD -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j DROP

If I test simple cmd ex: iptables -I FORWARD -p tcp --dport 443 -d 1.1.1.1 -j DROP , it works
Do you know the caused with Linux's Bridged-mode?
I think another Linux distr (Ubuntu/Centos) also has the same problem
BRs

**Comment by luigi1809** [comment]
try iptables -I INPUT -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j DROP for bridging

**Comment by whitetiger21022014** [comment]
Just tested: iptables -I INPUT -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j DROP , it doesn't work
Only OUTPUT works

**Comment by luigi1809** [comment]
what's wrong with using OUTPUT? It should drop as desired

**Comment by whitetiger21022014** [comment]
@Lochnair 
I Just tested 3 cases: 1 Ubuntu 16 as new server with 1 NIC card, and OpenWRT in Routed mode/Bridged mode
iptables -I INPUT -p tcp -**-dport** 443 -m tls --tls-host "www.facebook.com" -j DROP
iptables -I INPUT -p tcp **--sport** 443 -m tls --tls-host "www.facebook.com" -j DROP

Both INPUT commands above still does not BLOCK that domain, could you try INPUT chain?
OUTPUT always works

**Comment by luigi1809** [comment]
@whitetiger21022014 
You should try this project https://github.com/luigi1809/webfilter-ng/

Check section "filtering based on whitelist / blacklist"

**Comment by LGA1150** [comment]
By default OpenWrt doesn't filter bridged traffic with iptables
To enable that, you need `kmod-br-netfilter`, and `net.bridge.bridge-nf-call-iptables=1` in `/etc/sysctl.conf`

**Comment by whitetiger21022014** [comment]
It already installed kmod-br-netfilter - 4.9.120-1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1

iptables -I FORWARD -p tcp --dport 443 -j DROP will block all, it means, OpenWRT pass bridged IPv4 traffic to iptables' chains.
But it can't block with option:  -p tcp --dport 443 -m tls --tls-host
Thank you
