### ISSUE TITLE
Match by server certificate

### ISSUE THREAD

**Issue by Lochnair** [Lochnair/xt_tls#3]
Currently it's only possible to match on the SNI extension in the client hello, and while that's the preferred method of matching, it would be great to be able to fall back on the server certificate should the client not support SNI.

The major headache with getting this to work is the fact that the certificates are to big to be sent in one packet, and thus we have to reassemble them. I've no idea how to go about doing that.

**Comment by elico** [comment]
@Lochnair This kind of work is not supposed to be a kernel module job.
It's more of a proxy job to do this kind of things.
I wrote some GoLang code that does some of this but if you will be willing to touch this you will need to do a lot of work which I think should be invested in other things(dinner, friends, other important things).
