### ISSUE TITLE
TLS vhost redirection, could it be scalable?

### ISSUE THREAD

**Issue by vanrein** [Lochnair/xt_tls#36]
This is a very nice module; I was designing it in my mind and decided someone must have had the same idea :)

What I am wondering is if this could be used for TLS-level vhost mapping, and how well that would scale.  For instance, ipsets are great for scaling matches but they won't help with a mapping that depends on the mapping itself.  Could such data be supplied through other parts of the `xt_tls` module?

To illustrate, what I am considering to do is this:

 1. Translate the small external IPv4 space to a small internal IPv6 space with stateless NAT64
 2. Use `ip6tables` to redirect incoming ports to actual IPv6 `address:port` combinations
 3. Split this even further for SNI-based vhosting, with `xt_tls` or a user-space program

The idea is to use a tight IPv4-space as well as possible, but have IPv6 as the normal internal network.  Efficiency and reliability would be the concerns driving the choice between `xt_tls` and a user-space program.

**Comment by Lochnair** [comment]
Rather late, but for anyone stumbling upon this issue you're likely going to be disappointed if you're aiming to redirect TLS or similar with this module.

By the time xt_tls gets its hands on the client handshake the TCP connection is already established, so you can't change the destination without breaking it.

To my knowledge the only way is to run some sort of proxy and redirect all TLS traffic through that.
