### ISSUE TITLE
Whitelisting domain-name

### ISSUE THREAD

**Issue by jigneshparmar243** [Lochnair/xt_tls#43]
Iptables rule with xt_tls work correctly, but when I am using  iptables rule with -j drop instead of -j drop.
 Drop forwarding chain policy.

It's not working 
It just allowing specific domain-name and dropping it's sub-domain. Whatever I mentioned in whitelist rule.

So is it any possibility to resolve this issues.
Please answer .

**Comment by Lochnair** [comment]
Not a bug, just requires more to configure it correctly for this use case: https://github.com/Lochnair/xt_tls/issues/58#issuecomment-1526513294
