### ISSUE TITLE
SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175

### ISSUE THREAD

**Issue by babasyedm** [Lochnair/xt_tls#44]
I am trying xt_tls on Ubuntu 16.04, and encountered following error message

root@ip-172-31-92-106:/home/ubuntu/xt_tls# make install
make -C ipt DESTDIR=/ install
make[1]: Entering directory '/home/ubuntu/xt_tls/ipt'
make[1]: pkg-config: Command not found
install -D -v -m 644 libxt_tls.so /
removed '/libxt_tls.so'
'libxt_tls.so' -> '/libxt_tls.so'
make[1]: Leaving directory '/home/ubuntu/xt_tls/ipt'
make -C src DESTDIR=/ install
make[1]: Entering directory '/home/ubuntu/xt_tls/src'
make -C /lib/modules/4.4.0-1117-aws/build SUBDIRS=/home/ubuntu/xt_tls/src INSTALL_MOD_PATH=/ modules_install
make[2]: Entering directory '/usr/src/linux-headers-4.4.0-1117-aws'
  INSTALL /home/ubuntu/xt_tls/src/xt_tls.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.4.0-1117-aws
make[2]: Leaving directory '/usr/src/linux-headers-4.4.0-1117-aws'
depmod -a
make[1]: Leaving directory '/home/ubuntu/xt_tls/src'

Please help with the SSL ERROR

**Comment by Lochnair** [comment]
I don't have knowledge about this unfortunately. I believe the error is related to secure boot signing,
so you would have to look into how that works when compiling kernel modules

AFAIK this isn't anything we need to handle in the module itself, so closing this
