### ISSUE TITLE
no rule to process a target relocs_32.c

### ISSUE THREAD

**Issue by rickfalcao** [Lochnair/xt_tls#49]
DKMS make.log for xt_tls-0.3.3 for kernel 5.11.0-34-generic (x86_64)
Tue Sep 21 02:09:04 +03 2021
make[1]: Entering directory '/var/lib/dkms/xt_tls/0.3.3/build'
make -C ipt
make[2]: Entering directory '/var/lib/dkms/xt_tls/0.3.3/build/ipt'
cc -I../src -fPIC   -c -o libxt_tls.o libxt_tls.c
cc -shared -o libxt_tls.so libxt_tls.o;
rm libxt_tls.o
make[2]: Leaving directory '/var/lib/dkms/xt_tls/0.3.3/build/ipt'
make -C src
make[2]: Entering directory '/var/lib/dkms/xt_tls/0.3.3/build/src'
make -C /lib/modules/5.11.0-34-generic/build SUBDIRS=/var/lib/dkms/xt_tls/0.3.3/build/src modules
make[3]: Entering directory '/usr/src/linux-headers-5.11.0-34-generic'
make[4]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
make[3]: *** [arch/x86/Makefile:211: archscripts] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.11.0-34-generic'
make[2]: *** [Makefile:10: default] Error 2
make[2]: Leaving directory '/var/lib/dkms/xt_tls/0.3.3/build/src'
make[1]: *** [Makefile:7: all] Error 2
make[1]: Leaving directory '/var/lib/dkms/xt_tls/0.3.3/build'

why is this happening? I've tried several solutions and nothing works

**Comment by Lochnair** [comment]
If you replace SUBDIRS= with M= in the Makefile that seems to fix that particular error.
https://github.com/Lochnair/xt_tls/blob/ef9920ef88fefb2d3513ac50b4a4f16e315852ba/src/Makefile#L10-L16

However we also need to fix compatibility with newer kernels, as it errors out because something we use has changed.
Haven't had time to look into that yet.

**Comment by rickfalcao** [comment]
thanks,

I did that and also changed a snippet of the "hotset.c" file 


static struct proc_ops proc_fops = {
    .proc_open = seq_file_open,
    .proc_read = seq_read,
    .proc_write = proc_write,
    .proc_release = seq_release,
};



, then the installation is completed , but now i have the following error:

iptables v1.8.4 (legacy): Couldn't load match `tls':No such file or directory

**Comment by Lochnair** [comment]
Don't know if you figured this out, but it sounds like the xtables module wasn't compiled and installed.

If the userspace component isn't there you won't be able to add rules using the module. Did you run make in the src folder or in the parent (root) folder?

**Comment by rickfalcao** [comment]
yes, I got this. The installation was indeed complete, but the module was not loaded, because I was trying to do this inside a container, and so the module was not loaded.

**Comment by rickfalcao** [comment]
however , I installed on a VM , and I noticed a detail : if the rule is created after accessing a site that was open , the packages are not dropped

**Comment by rickfalcao** [comment]
i just use like this 
sudo iptables -A OUTPUT -p tcp --dport 443 -m tls --tls-host "*.facebook.com" -j DROP

**Comment by Lochnair** [comment]
Commited the fix for the first error and added compatibility for 5.6+ kernels in master
