### ISSUE TITLE
Problem installing new drivers for Realtek network card on Linux Mint 

### ISSUE THREAD

**Issue by Lava8005** [Lochnair/xt_tls#55]
Hi,
i had been having issues with my network card as after being connected to net for 3-4 minutes the connectivity would be gone and to regain connectivity i had to turn off wireless and turn it back on.
I went to many threads and tried to reinstall the drivers but i encountered errors in the process ,
to install the driver r8168 i have to run the autorun.sh which gives the following -:

root@usr-HP-ProBook-4440s:/home/usr/r8168# ./autorun.sh

Check old driver and unload it.
Build the module and install
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
Warning: modules_install: missing 'System.map' file. Skipping depmod.
DEPMOD 5.4.0-121-generic
load module r8168
Updating initramfs. Please wait.
update-initramfs: Generating /boot/initrd.img-5.4.0-121-generic
Completed.

**Comment by Lava8005** [comment]
Please help me @Lochnair

**Comment by damo2929** [comment]
whats this got to do with this module ?
