### ISSUE TITLE
Module verification failed

### ISSUE THREAD

**Issue by obordeau** [Lochnair/xt_tls#60]
Hello! 
I tried to install the module and the installation seems to work. But when I tried to block traffic to Facebook with the rule "sudo iptables -A OUTPUT -p tcp --dport 443 -m tls --tls-host "www.facebook.com" -j DROP" it doesn't work.
Then when I tried to debug with "make debug" and launch dmesg, I have the following error : 
[13007.227985] xt_tls: loading out-of-tree module taints kernel.
[13007.228042] xt_tls: module verification failed: signature and/or required key missing - tainting kernel
Does somebody have any idea why it's not working?
Thank you !

**Comment by bgcorreia** [comment]
@obordeau the place where you are using the iptables is it a gateway of your network? if yes, usually the traffic is not addressed for it, so in this case that traffic not pass in OUTPUT chain of the filter table.

You need add that fule in another table/chain (for instance, mangle/PREROUTING), check the iptables flow here: https://www.csie.ntu.edu.tw/~b93070/CNL/v4.0/CNLv4.0.files/image2070.gif

**Comment by Lochnair** [comment]
This is due to secure boot required signed binaries which includes kernel modules. When I was testing the fix for newer kernels, I had to sign the module to get it to load, see: https://wiki.ubuntu.com/UEFI/SecureBoot/Signing, specifically the kmodsign part.
