### ISSUE TITLE
cannot find glob.h under debian

### ISSUE THREAD

**Issue by ajmmartinez** [Lochnair/xt_tls#7]
Hi,

I know maybe this is a question not of xt_tls, but any help would be appreciated.

I'm getting stucked trying to compile, the message says that the system cannot find the module glob.h
I'm compiling it on a debian system  "Linux test 3.16.0-4-586 #1 Debian 3.16.7-ckt25-2 (2016-04-08) i686 GNU/Linux"

The error that I've got is this (I know it's a .h file but I cannot find it, or the package that contains it):

root@test:~/xt_tls# make
make -C ipt
make[1]: Entering directory '/root/xt_tls/ipt'
make libxt_tls.so
make[2]: Entering directory '/root/xt_tls/ipt'
cc -I../src -fPIC   -c -o libxt_tls.o libxt_tls.c
cc -shared -o libxt_tls.so libxt_tls.o;
rm libxt_tls.o
make[2]: Leaving directory '/root/xt_tls/ipt'
make[1]: Leaving directory '/root/xt_tls/ipt'
make -C src
make[1]: Entering directory '/root/xt_tls/src'
make -C /lib/modules/3.16.0-4-586/build SUBDIRS=/root/xt_tls/src modules
make[2]: Entering directory '/usr/src/linux-headers-3.16.0-4-586'
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-586'
  CC [M]  /root/xt_tls/src/xt_tls.o
**/root/xt_tls/src/xt_tls.c:13:24: fatal error: linux/glob.h: No such file or directory
 #include <linux/glob.h>**
                        ^
compilation terminated.
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:268: recipe for target '/root/xt_tls/src/xt_tls.o' failed
make[5]: *** [/root/xt_tls/src/xt_tls.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/Makefile:1353: recipe for target '_module_/root/xt_tls/src' failed
make[4]: *** [_module_/root/xt_tls/src] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[3]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-3.16.0-4-586'
Makefile:9: recipe for target 'default' failed
make[1]: *** [default] Error 2
make[1]: Leaving directory '/root/xt_tls/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

Thanks a lot

**Comment by Lochnair** [comment]
Yeah, that's because linux/glob.h was added in kernel version 3.17, so it doesn't exist for your kernel.
Luckily it contains just a single function, so I've pushed a commit on the _develop_ branch including the function in my source tree.

Could you try that and see if there's anything else that needs to be backported?

**Comment by ajmmartinez** [comment]
Thanks for your reply.
I'm testing, but right now the make and make install works without problem.

I'll do some other tests and if I see something I'll tell you, ok ?
Thanks again.

2017-06-16 14:24 GMT-03:00 Nils Andreas Svee <notifications@github.com>:

**Comment by Lochnair** [comment]
I'll close this issue then. Hopefully there's no need to do more *shudders* backporting.
